apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-web
  namespace: obs-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: obs-web
  template:
    metadata:
      labels:
        app: obs-web
    spec:
      containers:
      - name: nginx
        # The marker below allows Flux to update the tag automatically
        image: ondrejnr/obs-web:1.0.0 # {"$imagepolicy": "flux-system:obs-web-policy"}
        ports:
        - containerPort: 80
