apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: obs-web-repo
  namespace: flux-system
spec:
  image: ondrejnr1/obs-web
  interval: 1m0s
  secretRef:
    name: dockerhub-auth
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: obs-web-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: obs-web-repo
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: obs-git-automation
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      # ZJEDNODUŠENÁ ŠABLÓNA (Fix pre can't evaluate field error):
      messageTemplate: 'chore: automated image update'
    push:
      branch: main
  update:
    path: ./infra/environments/dev
    strategy: Setters
