apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: ci-cd
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-token
  namespace: ci-cd
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-actions-role
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: ci-cd
